import type { Metadata } from 'next';
import SessionProviders from '@/providers/SessionProviders'
import './globals.css';

export const metadata: Metadata = {
  title: 'SkiLogin Academy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SessionProviders>
          {children}
        </SessionProviders>
      </body>
    </html>
  );
}
